Update android-guide.md to reflect working Example (#704)
After hours of this package not working due to various errors, I found my problem lies in this guide

following this guide I ended up with build error:
```
Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzcfb`.
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:89)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:60)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:64)
        ... 10 more


> Task :app:transformClassesWithDexBuilderForProdDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForProdDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/Pavel/.gradle/caches/transforms-1/files-1.1/firebase-analytics-impl-11.4.2.aar/38df48ccec649ec4a1c0d4fe925a89bb/jars/classes.jar
```

I was able to build my project after manipulating the `app/build.gradle` like so:
```
implementation (project(':react-native-device-info')){
        exclude group: 'com.google.android.gms'
    }
    implementation (project(':react-native-google-signin')){
        exclude group: 'com.google.android.gms'
    }
```
but that will cause a crash on start:
```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
Process: com.app, PID: 4124
java.lang.NoClassDefFoundError: com.google.android.gms.common.SignInButton
```

only after noticing the different versions in the Example the app builds and starts, so I propose changing it also in here, I don't know how it works for other people (there is no issue).
I include all the errors here in case someone ends up with the same troubles and what was the cause on my side.